apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
   leaderElect: false
profiles:
   - schedulerName: my-scheduler
     pluginConfig:
       - args:
           apiVersion: kubescheduler.config.k8s.io/v1
           kind: NodeResourcesFitArgs
           scoringStrategy:
               resources:
                  - name: cpu
                    weight: 5
                  - name: memory
                    weight: 5
               type: MostAllocated
         name: NodeResourcesFit
     plugins:
       score:
           disabled:
               - name: PodTopologySpread
               - name: InterPodAffinity
               - name: TaintToleration
               - name: NodeResourcesBalancedAllocation
               - name: ImageLocality
               - name: NodeAffinity
           enabled:
               - name: NodeResourcesFit
                 weight: 5
