apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      schedulerName: my-scheduler
      containers:
      - name: stress
        image: ntumpi/stress:latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "1.5"
          limits:
            memory: "300Mi"
            cpu: "3"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stress-service
spec:
  selector:
    app: stress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
